compute:
  solver:
    public:
      mode: lbfgsb
      use_warmup: true
  passes:
    capture: { every: 1, final_always: true }
    grad_clip: { enable: false, norm_max: 1000.0 }
    step_limit: { max_step_norm: null }
  weights: {}
