# compute.internals.yaml (CLEANED)
# 内部参数：数值稳定与公差，尽量不暴露给普通用户。已移除未实现的键：
# - compute.solver.internals.clip.*
# - compute.solver.internals.stability.exp_clip
# 已添加：
# - compute.passes.nan_guard.e_fallback  # NaN/Inf 兜底能量，通常不需要修改

compute:
  solver:
    internals:
      stability:
        eps_norm: 1.0e-12       # 向量范数时的数值 eps
  eps:
    numeric: 1.0e-12            # 全局数值 eps
    dist: 1.0e-06               # 距离计算 eps
    abs: 0.001                  # 绝对公差阈值
    proj: 1.0e-09               # 投影/约束 eps
  passes:
    nan_guard:
      e_fallback: 0.0           # 发生 NaN/Inf 时使用的兜底能量
