# compute.public.yaml (CLEANED)
# 公开参数：创作者/高级用户常改。已移除未被实现消费的键：
# - compute.solver.public.log_level
# 已添加：
# - compute.public.forces.area.cross.use_legacy_gate: false  # 为旧 gate 兼容开关；默认关闭

compute:
  solver:
    public:
      mode: hybrid            # 求解器选择：lbfgsb | semi_newton | hybrid
      use_warmup: true        # 是否在正式求解前做预热（warm-up）
      # 全局日志等级：none | info | debug
      log_level: info

  passes:
    capture:
      every: 1                # 录帧频率；1 表示每步都录
      mode: both              # both|energy_only|state_only（若实现仅支持 both，可后续收紧）
      final_always: true      # 无论如何总是记录最终一帧
      limit: null             # 最多记录帧数；null 表示不限制
    calibration:
      enable: true           # 你可按需改 true
    action:
      enable: true            # 是否执行场景 action
    geom_preproc:
      enable: true
      tiny_eps: 1.0e-9
    grad_clip:
      enable: true           # 是否启用梯度裁剪
      max_norm: 1000.0        # L2 范数上限
      max_abs: null           # 每分量绝对值上限（可选）
    nan_guard:
      enable: true            # 数值保护开关
    step_limit:
      max_step_norm: null     # 单步位移上限（像素或坐标单位）

  public:
    forces:
        pl:
          rect:
            enable: true
            k_out: 50.0
            k_in: 300.0
            kernel: { model: inv_pow, exponent: 2.0, soft_eps: 1.0e-6 }
            beta: { sep: 6.0, in: 6.0 }
            g_eps: 1.0e-6
            eps: { abs: 0.001 }
        ln:
          rect:
            enable: false
            k_out: 200.0
            k_in: 300.0
            kernel: { model: inv_pow, exponent: 2.0, soft_eps: 1.0e-6 }
            beta: { sep: 6.0, in: 6.0 }
            g_eps: 1.0e-6
            eps: { abs: 0.001 }
        ll:
          rect:
            enable: false
            k_ll_repulse: 120.0
            k_ll_inside: 400.0
            ll_edge_power: 2.0
            ll_edge_eps: 0.5
            beta_softabs_dir: 6.0
            beta_softplus_sep: 6.0
            eps: { abs: 0.001 }
          disk:
            enable: true
            k_ll_repulse: 240.0
            ll_edge_power: 1.3
            ll_edge_eps: 0.5
            beta_softplus_sep: 6.0
            ll_center_eps: 0.001
            ll_disk_mode: max
            eps: { abs: 0.001 }
        area:
          cross:
            enable: true
            k_cross: 400.0
            use_legacy_gate: false     # 旧 gate 兼容开关（默认关闭）
            min_gap: 0.5
            tan_gate: { eta: 2.0, slack: 0.0 }
            gate_min_interior: 0.0
            tan_cap_scale: 1.0
            outside_weight: 0.1
          embed:
            enable: true
            k_embed: 120.0
            ratio_in: 0.9
            in_decay: 0.2
            out_decay: 0.1
          softout:
            enable: false
            k_push: 20.0
            pad: 0.1
            y_down: 0.0
        boundary:
          wall:
            enable: true
            k_wall: 300.0
            alpha: 1.0
        focus:
          attract:
            enable: true
            k_attract: 5.0
            intro_times: 3
            center: [0.44, 0.39]
            wh: [0.2, 0.1]
            sigma: 0.2
        anchor:
          spring:
            enable: true
            k_anchor_spring: 200.0
            k_anchor_occlusion: 300.0
            anchor_spring_kind: "linear"  # logcosh | linear
            anchor_spring_alpha: 3.0
            anchor_r0_points: 60.0
            anchor_r0_lines: 60.0
