# compute.tuning.yaml (CLEANED)
# 细调参数：数值调优、终止条件等。已移除未实现的键：
# - compute.solver.tuning.lbfgsb.m
# - compute.solver.tuning.anti_jump.step_cap_px
# 已添加（代码中有读取）：
# - compute.solver.tuning.lbfgsb.lbfgs_pgtol
# - compute.solver.tuning.lbfgsb.lbfgs_maxiter

compute:
  passes:
    calibration:
      enable: true               # 是否启用自动力平衡
      clip_q: 0.995              # 剪裁分位数
      p_q: 0.95                  # 目标分位数
      clamp_min: 0.33            # 缩放下限
      clamp_max: 3.0             # 缩放上限
      min_act: 0.05              # 激活比例阈值
      hysteresis: 0.25           # 迟滞带
      ema_alpha: 1.0             # EMA 系数（1.0 表示立即应用）
      base_term: focus.attract   # 基准力项
      target_rel:                # 各力项相对于基准力的目标比例
        ll.rect: 2.5             # label-label rectangle repulsion
        ll.disk: 2.5             # label-label disk repulsion
        boundary.wall: 3.0       # canvas boundary wall
        anchor.spring: 2.0       # anchor spring
        pl.rect: 1.2             # point-label rectangle repulsion
        ln.rect: 1.2             # line-label rectangle repulsion
        area.embed: 2.0          # area embedding term
        area.cross: 4.0          # area cross term
        area.softout: 0.6        # area outside soft penalty
        focus.attract: 1.0       # focus attraction (基准力)
  solver:
    tuning:
      lbfgsb:
        lbfgs_pgtol: 1.0e-9     # 投影梯度阈值（若后续统一到 SciPy 语义，可在装配处映射到 gtol）
        lbfgs_maxiter: 400      # 最大迭代步数（可映射到 maxiter）

      hybrid:
        sn_max_outer: 5         # 半隐式牛顿热启动步数
        lbfgs_maxiter: 400      # 主阶段 L-BFGS 迭代数
        sn_post_max_outer: 5    # L-BFGS 异常终止后的回退步数

      semi_newton:
        sn_max_outer: 30
        sn_dt: 1.0
        sn_hvp_eps: 1.0e-4
        sn_cg_maxiter: 200
        sn_cg_rtol: 1.0e-5
        sn_cg_atol: 0.0
        sn_lm0: 1.0e-3
        sn_gtol: 1.0e-5

      stop:
        ftol: 1.0e-9
        xtol: 1.0e-9
        max_stall_iters: null

      warmup:
        steps: 10
