# compute.tuning.yaml (CLEANED)
# 细调参数：数值调优、终止条件等。已移除未实现的键：
# - compute.solver.tuning.lbfgsb.m
# - compute.solver.tuning.anti_jump.step_cap_px
# - compute.passes.calibration.*（未启用的校准 pass）
# 已添加（代码中有读取）：
# - compute.solver.tuning.lbfgsb.lbfgs_pgtol
# - compute.solver.tuning.lbfgsb.lbfgs_maxiter

compute:
  solver:
    tuning:
      lbfgsb:
        lbfgs_pgtol: 1.0e-9     # 投影梯度阈值（若后续统一到 SciPy 语义，可在装配处映射到 gtol）
        lbfgs_maxiter: 400      # 最大迭代步数（可映射到 maxiter）

      semi_newton:
        sn_max_outer: 30
        sn_dt: 1.0
        sn_hvp_eps: 1.0e-4
        sn_cg_maxiter: 200
        sn_cg_rtol: 1.0e-5
        sn_cg_atol: 0.0
        sn_lm0: 1.0e-3
        sn_gtol: 1.0e-5

      stop:
        ftol: 1.0e-9
        xtol: 1.0e-9
        max_stall_iters: null

      warmup:
        steps: 10
