# compute.public.yaml (CLEANED)
# 公开参数：创作者/高级用户常改。已移除未被实现消费的键：
# - compute.solver.public.log_level

compute:
  solver:
    public:
      mode: hybrid            # 求解器选择：lbfgsb | semi_newton | hybrid
      use_warmup: true        # 是否在正式求解前做预热（warm-up）
      # 全局日志等级：none | info | debug
      log_level: info

  passes:
    capture:
      every: 1                # 录帧频率；1 表示每步都录
      mode: both              # both|energy_only|state_only（若实现仅支持 both，可后续收紧）
      final_always: true      # 无论如何总是记录最终一帧
      limit: null             # 最多记录帧数；null 表示不限制
    calibration:
      enable: false           # 你可按需改 true
    action:
      enable: true            # 是否执行场景 action
    label_relax:
      enable: true
      step_size: 2.0         # 每步放松步长
      step_count: 5          # 放松步数
    geom_preproc:
      enable: true
      tiny_eps: 1.0e-9
    grad_clip:
      enable: true           # 是否启用梯度裁剪
      max_norm: 1000.0        # L2 范数上限
      max_abs: null           # 每分量绝对值上限（可选）
    nan_guard:
      enable: true            # 数值保护开关
    step_limit:
      max_step_norm: null     # 单步位移上限（像素或坐标单位）

  public:
    forces:
        pl:
          rect:
            enable: true
            k_out: 50.0
            k_in: 300.0
            kernel: { model: inv_pow, exponent: 2.0, soft_eps: 1.0e-6 }
            beta: { sep: 6.0, in: 6.0 }
            g_eps: 1.0e-6
            eps: { abs: 0.001 }
        ln:
          rect:
            enable: false
            k_out: 200.0
            k_in: 300.0
            kernel: { model: inv_pow, exponent: 2.0, soft_eps: 1.0e-6 }
            beta: { sep: 6.0, in: 6.0 }
            g_eps: 1.0e-6
            eps: { abs: 0.001 }
        ll:
          rect:
            enable: false
            k_ll_repulse: 120.0
            k_ll_inside: 400.0
            ll_edge_power: 2.0
            ll_edge_eps: 0.5
            beta_softabs_dir: 6.0
            beta_softplus_sep: 6.0
            eps: { abs: 0.001 }
          disk:
            enable: true
            k_ll_repulse: 240.0
            ll_edge_power: 1.3
            ll_edge_eps: 0.5
            beta_softplus_sep: 6.0
            ll_center_eps: 0.001
            ll_disk_mode: max
            eps: { abs: 0.001 }
        area:
          cross:
            enable: true                # 启用区域交叉力项
            k_cross: 400.0              # 力项权重，数值越大越不允许交叉
            min_gap: 0.5                # 区域间的最小间隔（像素）
            eta: 4.0                    # 切向门函数平滑系数
            alpha: 0.7                  # 法向穿透惩罚的锐度
            tan_cap_scale: 1.0          # 切向门函数强度上限缩放
            gate_min_interior: 0.0      # 区域内部门函数的下限，避免零梯度
            kappa: 8.0                  # 内部指示函数的斜率
            beta_smax: 4.0              # 切向与内部门函数的平滑最大参数
            L_floor: 1.0e-3             # 边长工程下限（坐标单位）
            deriv_clip: 1.0e3           # 导数夹取阈值
            use_legacy_gate: false      # 兼容字段，不再启用 legacy 实现
            use_logcosh: true           # 是否使用 logcosh 能量模型（否则为二次型）
            sat_p0: 2.0                 # logcosh 饱和阈值
            kernel:                     # 门函数核参数
              model: logcosh           # 核模型
              gate_gamma: 8.0          # 门函数斜率
              exponent: 1.0            # 模型指数
              soft_eps: 1.0e-6         # 平滑 epsilon
            eps:                        # 数值 epsilon 设置
              abs: 0.001               # 软绝对值 eps
          embed:
            enable: true
            k_embed: 120.0
            ratio_in: 0.9
            in_decay: 0.2
            out_decay: 0.1
          softout:
            enable: false
            k_push: 20.0
            pad: 0.1
            y_down: 0.0
        boundary:
          wall:
            enable: true
            k_wall: 300.0
            alpha: 3.0
        focus:
          attract:
            enable: true
            k_attract: 50.0
            intro_times: 3
            center: [0.44, 0.39]
            wh: [0.2, 0.1]
            sigma: 0.2
        anchor:
          spring:
            enable: true
            k_anchor_spring: 200.0
            k_anchor_occlusion: 300.0
            anchor_spring_kind: "logcosh"  # logcosh | linear
            anchor_spring_alpha: 3.0
            anchor_r0_points: 60.0
            anchor_r0_lines: 60.0
