data:
  source: generate
  generate:
    counts: { points: 5, lines: 1, areas: 1 }
    labels: null               # if null -> default to sum(counts); NOT a constraint
    steps: 5
    frame_size: [800, 600]
    seed: 7
    spacing: { min_point_dist: 8.0, margin: 12.0 }
    shapes:  { area_fallback: polygon, line_min_vertices: 2 }
    route_gen:
      min_vertex_spacing_scale: 1.0
      inset_margin_scale: 0.05
      segment_len_scale: 0.10
      angle_noise_sigma: 0.0
    area_gen:
      inset_margin_scale: 0.04
      min_edge_spacing_scale: 0.04
      n_vertices_min: 3
      n_vertices_max: 7
    anchors:
      policy: round_robin
      modes: { line: midpoint, area: centroid }
    # label_mix: { point: 1.0, line: 1.0, area: 1.0 }
  behaviors: []
  load: { path: "" }
