public:
  mode: lbfgsb                  # allowed: lbfgsb|simple|hybrid|newton
  use_autocal: false
  use_warmup: true
  use_retry: false
  use_topk_sources: false
  profile: basic                # also accepts: balanced|stable|cinematic
  force_level: medium
