solver:
  mode: hybrid                  # allowed: lbfgsb|simple|hybrid|newton
  use_autocal: false
  use_warmup: true
  use_retry: false
  use_topk_sources: false
  profile: basic                # also accepts: balanced|stable|cinematic
  force_level: medium

data:
  source: generate

# if source == "generate":
  generate:
    num_points:  11        # >=0
    num_lines:   1        # >=0
    num_areas:   2        # >=0
    num_labels:          # >=1 (optional; infer if missing)
    num_steps:   19        # >=1 (required)
    frame_size:  [1080, 1920]   # optional; default [1920.0,1080.0]
    seed:        123      # optional

# if source == "load":
  load:
    path: "path/to/snapshot.npz|.json"   # required

terms:
  anchor:
    spring: { k: 6.0, r0: 62.0, damping: 0.0 }
  focus: { k: 0.5, sigma: 40.0 }
  boundary: { k: 2.0, softness: 4.0 }
  label_label_repulse: { k: 0.4, d0: 10.0, exponent: 2.0 }
  line_label_repulse:  { k: 0.3, d0: 10.0, exponent: 2.0 }
  point_label_repulse: { k: 0.3, d0: 10.0, exponent: 2.0 }
  label_label_inside:  { k: 0.2, margin: 4.0 }
  line_label_inside:   { k: 0.2, margin: 4.0 }
  point_label_inside:  { k: 0.2, margin: 4.0 }
  area_cross:          { k: 1.2, sigma: 6.0 }
  area_embed:          { k: 0.8, sigma: 6.0, edge_bias: 0.0 }
