data:
  random:
    route_gen: { k_sigma_bound: 5, max_retry: 50 }
    area_gen:  { k_sigma_bound: 5, max_retry: 50 }

solver:
  internals:
    eps: { div: 1e-9, sqrt: 1e-9, proj: 1e-9 }
    clip: { force_abs_max: 1e6, energy_abs_max: 1e6 }
    temperature: { min: 1e-3, max: 10.0 }
    stability:
      softplus_limit: 40.0
      logsumexp_floor: -40.0
      eps_sigma: 1.0e-3
      eps_norm: 1.0e-12
      exp_clip: 40.0
      area_eps: 1.0e-12
