solver:
  merge:        { mode: sum, temperature: 1.0 }
  normalize:    { kind: l2 }
  threshold:    { abs: null, rel: null }
  topk:         { enable: false, k: 4, min_share: 0.0 }
  lbfgsb:       { m: 10, maxiter: 300 }
  stopping:     { gtol: 1.0e-4 }
  anti_jump:    { step_cap_px: 30.0 }
  clamp:        { optimize_force_max: 1.0e6 }
  warmup:       { steps: 1 }

terms:
  anchor:
    spring: { k: 5.0 }

data:
  random:
    route_gen:
      mean_length_scale: 0.30
