show: true
panels:
  layout: true
  forces: true
  info: true
  field: true
field:
  mode: surface3d  # "heatmap" | "surface3d"
  resolution: 40  # grid size per axis; used for both heatmap and 3D
  terms: ["focus.attract"]
  aggregate: norm  # or "div"
  log_scale: false
  fallback_splat: true
layout:
  colors:
    points: "#2E86DE"
    lines: "#10AC84"
    areas: "#F1C40F"
    label_fill: "#FFFFFF"
    label_edge: "#2D3436"
    anchor_line: "#95A5A6"
    anchor_marker_face: "#FFFFFF"
    anchor_marker_edge: "#2D3436"
  line_width: 1.0
  anchor_line_width: 1.0
  area_face_alpha: 0.30
  area_edge_width: 1.0
  label_edge_width: 1.0
  label_fontsize: 10
  anchor_marker_size: 5.0
forces:
  colors:
    ll.rect: "#1f77b4"
    boundary.wall: "#ff7f0e"
    anchor.spring: "#2ca02c"
  component_arrow_lw: 2.2
  component_arrow_scale: 16.0
  component_fontsize: 11
  total_arrow_scale: 20
  total_arrow_lw: 2.5
force_view:
  show_vectors: true
  clamp_force_max: 1000.0
picker:
  enable: false
surface3d:
  enable: false
export:
  enable: false
