panels:
  layout: true     # show layout panel
  forces: false    # show force panel
colors:
  background: "#ffffff"  # canvas background
linewidths:
  layout: 1.0      # layout line width
  force: 1.0       # force vector line width
layout:
  anchor_marker_size: 4.0  # default anchor marker size
force_view:
  show_vectors: true  # display force arrows
  clamp_force_max: 1000.0  # max force magnitude for display
picker:
  enable: false    # interactive picker
surface3d:
  enable: false    # 3D surface view
export:
  enable: false    # export figures
