enable: true
export_stride: 1
figure_size: [22, 10]
dpi: 120

panels: { main: true, force: true, timeline: true, info: true }
layers: { points: true, lines: true, areas: true, labels: true }

layout:
  grid: [1, 3]
  aspect_mode: fit            # fit | fill | square
  line_width: 1.0
  area_face_alpha: 0.3
  area_edge_width: 1.0
  label_edge_width: 1.0
  label_fontsize: 10
  anchor_marker_size: 4.0
  colors:
    points: '#00D1FF'
    lines: '#FFC04D'
    areas: '#3DFA9A'
    label_fill: '#F2F2F2'
    label_edge: "#2F3175"
    anchor_line: '#D9D9D9'
    anchor_marker_face: '#F2F2F2'
    anchor_marker_edge: '#2F3175'

axes: { show_ticks: false, show_spines: true }

theme: dark
alpha:  { area_fill: 0.15, label_rect: 0.25 }
zorder: { points: 10, lines: 9, areas: 5, labels: 20 }

forces:
  colors:
    ll.rect: '#1f77b4'
    boundary.wall: '#ff7f0e'
    anchor.spring: '#2ca02c'
    focus: '#d62728'
    label_point: '#9467bd'
    label_line: '#8c564b'
    label_area: '#e377c2'
    area.softout: '#17becf'
    area.cross: '#bcbd22'
    points: '#1f9ed4'
    lines: '#f39c12'
    areas: '#27ae60'
  component_arrow_scale: 10.0
  component_arrow_lw: 1.0
  component_fontsize: 8
  total_arrow_scale: 12.0
  total_arrow_lw: 1.5

force_vectors: { show: true, density: auto, scale: 1.0, max_arrows: 400 }
force_breakdown: { topk: 8, show_total: true }
surface3d: { show: false, resolution: 128, clamp_z: [-5, 5] }

timeline: { show_iters: true, show_actions: true, scrubber: true }
picker: { tolerance_px: 25, draggable_labels: true }

export:
  out_dir: "outputs/viz"
  video: { enable: false, fps: 24, codec: "h264" }

numerics: { eps_label_overlap: 1e-6 }
